# Generated by Django 4.2.7 on 2025-12-18 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_reset_category_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='shop_produc_categor_d249e3_idx',
            old_name='shop_produc_categor_01dab4_idx',
        ),
    ]
